var mensaje = "hola mundo";
console.log(mensaje);
var numero = 100;
console.log(numero);
var esviernes = false;
console.log(esviernes);
var real = 1.43;
var binario = 5;
console.log(typeof binario);
var suma = real + binario + numero;
console.log(suma);
var comparacion;
comparacion = real > 2;
console.log(comparacion);
var octal = 37;
console.log(octal);
var cadena1 = "Hola";
var cadena2 = 'Hola';
var cadena3 = "El numero es ".concat(suma);
var unioncadena = cadena1 + cadena2;
console.log(typeof cadena1);
console.log(typeof cadena2);
console.log(unioncadena);
var arreglo1 = [1, 2, 3, 4];
var arreglo2 = [5, 6, 7, 8];
console.log(arreglo1);
console.log(arreglo2);
console.log(typeof arreglo1);
console.log(typeof arreglo2);
var arreglocadena = ["TS", "JS", "PHP"];
