/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gomez_Nuria;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author nuria
 */
public class T3P2E3 extends javax.swing.JFrame {

    /**
     * Creates new form T3P2E3
     */
    public T3P2E3() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        palabra = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        Subtitulo = new javax.swing.JLabel();
        Introducir = new javax.swing.JButton();
        BorrarV = new javax.swing.JButton();
        BorrarC = new javax.swing.JButton();
        tituloV = new javax.swing.JLabel();
        tituloC = new javax.swing.JLabel();
        ComboVocal = new javax.swing.JComboBox<>();
        ComboCon = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("ORDENA-PALABRAS");

        Subtitulo.setText("Nueva Palabra");
        Subtitulo.setToolTipText("");

        Introducir.setText("Introducir Palabra");
        Introducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntroducirActionPerformed(evt);
            }
        });

        BorrarV.setText("Borrar Palabra");
        BorrarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarVActionPerformed(evt);
            }
        });

        BorrarC.setText("Borrar Palabra");
        BorrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarCActionPerformed(evt);
            }
        });

        tituloV.setText("Palabras que empiezan por VOCAL");

        tituloC.setText("Palabras que empiezan por CONSONANTE");
        tituloC.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloC)
                    .addComponent(tituloV, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComboVocal, 0, 217, Short.MAX_VALUE)
                    .addComponent(ComboCon, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BorrarV, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BorrarC, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Subtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(palabra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Introducir)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Titulo)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Subtitulo)
                    .addComponent(palabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Introducir))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BorrarV)
                    .addComponent(tituloV)
                    .addComponent(ComboVocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloC)
                    .addComponent(ComboCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BorrarC))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void Borrar(JComboBox box) {//sirve para borrar del ComboBox escrito el elemento seleccionado
        int pos = box.getSelectedIndex();//toma la posicion del elemento seleccionado
        box.removeItemAt(pos);//lo borra
    }
    private void BorrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarCActionPerformed
        try {
            Borrar(ComboCon);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "No hay elemento para borrar..."
                    + "", "Oh no!", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_BorrarCActionPerformed

    private void BorrarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarVActionPerformed
        try {
            Borrar(ComboVocal);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "No hay elemento para borrar..."
                    + "", "Oh no!", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_BorrarVActionPerformed

    private void IntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntroducirActionPerformed

        String Palabra = palabra.getText();
        String vocales[] = {"a", "e", "i", "o", "u"};
        char letra = Palabra.charAt(0);
        if ((letra >= 65 && letra <= 90) || (letra >= 97 && letra <= 122)) {//revisa si es una letra o un caracter raro---
            String letraVS = Character.toString(letra);//Palabra.charAt(0)
            Boolean permiso = false;
            for (String vocal : vocales) {//revisa entre las vocales para mirar si esta dentro de estas
                if (letraVS.equalsIgnoreCase(vocal)) {//si esta
                    ComboVocal.addItem(Palabra);//se añade a vocales
                    permiso = true;//sino el boolean pasa a true...
                }

            }
            if (!permiso) {//...y cuando esta a true se añade a consonante
                ComboCon.addItem(Palabra);
            }
            palabra.setText("");//Se limpia cada vez que se escribe
        } else {//---y si no esta
            palabra.setText("");//limpia
            JOptionPane.showMessageDialog(this, "Esa palabra no empieza por vocal ni consonante..."
                    + "", "Error de palabra", JOptionPane.ERROR_MESSAGE);//te dice que eres bobo

        }

    }//GEN-LAST:event_IntroducirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(T3P2E3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(T3P2E3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(T3P2E3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(T3P2E3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new T3P2E3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarC;
    private javax.swing.JButton BorrarV;
    private javax.swing.JComboBox<String> ComboCon;
    private javax.swing.JComboBox<String> ComboVocal;
    private javax.swing.JButton Introducir;
    private javax.swing.JLabel Subtitulo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField palabra;
    private javax.swing.JLabel tituloC;
    private javax.swing.JLabel tituloV;
    // End of variables declaration//GEN-END:variables
}
