package interfaces;

import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Nuria
 */
public class act145_2 extends javax.swing.JFrame {

    /**
     * Creates new form act145_2
     */
    private int jugador;
    private int maquina;

    public act145_2() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    public act145_2(int NumJugador, int NumMaquina) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jugador = NumJugador;
        this.maquina = NumMaquina;
        QuienGana();
        MostrarNum();
    }

    private void QuienGana() {
        int res = this.jugador + this.maquina;
        if (res % 2 == 0) {
            WhoWins.setText("Ha ganado el Jugador!");
        } else {
            WhoWins.setText("Ha ganado la Maquina!");

        }
    }
    private void MostrarNum(){
        String cadena=Integer.toString(this.jugador);
        Jugador.setText(cadena);
        cadena=Integer.toString(this.maquina);
        Maquina.setText(cadena);
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jugador = new javax.swing.JLabel();
        WhoWins = new javax.swing.JLabel();
        Maquina = new javax.swing.JLabel();
        BotonVolver = new javax.swing.JButton();
        TituloJ = new javax.swing.JLabel();
        TituloM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        WhoWins.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        Maquina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        BotonVolver.setText("Volver");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        TituloJ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloJ.setText("JUGADOR");
        TituloJ.setToolTipText("Pares");

        TituloM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloM.setText("MAQUINA");
        TituloM.setToolTipText("Nones");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(Maquina, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(TituloJ, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TituloM, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonVolver)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(WhoWins, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloJ)
                    .addComponent(TituloM))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jugador)
                    .addComponent(Maquina))
                .addGap(18, 18, 18)
                .addComponent(WhoWins, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(BotonVolver)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        act145 VentanaJuego = new act145();
        VentanaJuego.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonVolver;
    private javax.swing.JLabel Jugador;
    private javax.swing.JLabel Maquina;
    private javax.swing.JLabel TituloJ;
    private javax.swing.JLabel TituloM;
    private javax.swing.JLabel WhoWins;
    // End of variables declaration//GEN-END:variables
}
